version: "3.8"

services:
  app:
    container_name: release-fetcher
    build: .
    ports:
      - "127.0.0.1:8888:8888"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8888
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SPOTIFY_REDIRECT_URI=http://127.0.0.1:8888/login/oauth2/code/spotify
